name: Update Localizations
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Gen version
        run: |
          versionPattern="^version\s*=\s*([0-9]{4}\.[0-9]{2}\.[0-9]{2})\.([0-9]+)$"
          newContent=""
          date=$(date +"%Y.%m.%d")
          newVersion="$date.0"

          if [[ $(file ./build.txt) == *"CRLF"* ]]; then
              IFS=$'\r\n'
          fi

          while read line
          do
              echo "line: |${line}|"
              if [[ "$line" =~ $versionPattern ]]; then
                  oldDate=${BASH_REMATCH[1]}
                  increment=${BASH_REMATCH[2]}

                  if [ "$oldDate" == "$date" ]; then
                      newVersion="$date.$((increment + 1))"
                  fi
              fi
          done < "./build.txt"

          echo "OLD_VERSION=${oldDate}.${increment}" >> $GITHUB_ENV
          echo "NEW_VERSION=${newVersion}" >> $GITHUB_ENV

      - name: Checkout
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -b $NEW_VERSION

      - name: Update Localizations
        run: |
          git submodule update --remote
          git add ./Localization/TMLHonyaku

      - name: Update build.txt
        run: |
          cat ./build.txt \
          | sed -e "s/^version\s*=\s*$OLD_VERSION/version = $NEW_VERSION/" \
          > ./build.txt
          git add ./build.txt

      - name: Commit
        run: |
          git commit -m "Update version to $NEW_VERSION"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update version to $NEW_VERSION"
          commit-message: "Update version to $NEW_VERSION"
          body: |
            This PR updates the version from $OLD_VERSION to $NEW_VERSION.
            @eva828Dev  Please approve this PR and upload the new version to the Steam Workshop.

            This is automatically generated by the Update Localizations workflow.
          branch: $NEW_VERSION
          base: master
          assignees: eva828Dev
